import ProjectDescription

let config = Config(
    plugins: [],
    generationOptions: .options(
        xcodeProjectName: "CleanEx",
        enableAutomaticXcodeSchemes: true,
        autogeneratedWorkspaceSchemes: .enabled(
            codeCoverageMode: .targets([]),
            testingOptions: [.parallelizable, .randomExecutionOrdering]
        )
    )
)